{
	"patcher" : {
		"fileversion" : 1,
		"appversion" : { "major" : 9, "minor" : 0, "revision" : 0, "architecture" : "x64", "modernui" : 1 },
		"classnamespace" : "box",
		"rect" : [ 50.0, 50.0, 900.0, 700.0 ],
		"bglocked" : 0,
		"openinpresentation" : 0,
		"default_fontsize" : 12.0,
		"default_fontname" : "Arial",
		"gridsize" : [ 15.0, 15.0 ],
		"gridsnaponopen" : 1,
		"objectsnaponopen" : 1,
		"statusbarvisible" : 2,
		"toolbarvisible" : 1,
		"description" : "Dream Xeno Box - Alien Percussion Voice Prototype",
		"boxes" : [
			{ "box" : { "id" : "obj-title", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 30.0, 10.0, 500.0, 24.0 ], "text" : "DREAM XENO BOX - Alien Percussion Voice Prototype", "fontsize" : 16.0, "fontface" : 1 } },
			{ "box" : { "id" : "obj-trig-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 30.0, 45.0, 100.0, 20.0 ], "text" : "== TRIGGER ==" } },
			{ "box" : { "id" : "obj-btn", "maxclass" : "button", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "bang" ], "patching_rect" : [ 30.0, 70.0, 40.0, 40.0 ] } },
			{ "box" : { "id" : "obj-click", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "signal" ], "patching_rect" : [ 30.0, 120.0, 42.0, 22.0 ], "text" : "click~" } },
			{ "box" : { "id" : "obj-ctrl-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 150.0, 45.0, 100.0, 20.0 ], "text" : "== CONTROLS ==" } },
			{ "box" : { "id" : "obj-pitch-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 150.0, 68.0, 40.0, 20.0 ], "text" : "PITCH" } },
			{ "box" : { "id" : "obj-pitch", "maxclass" : "number", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 200.0, 68.0, 50.0, 22.0 ], "minimum" : 10, "maximum" : 130 } },
			{ "box" : { "id" : "obj-pp", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 98.0, 80.0, 22.0 ], "text" : "prepend pitch" } },
			{ "box" : { "id" : "obj-decay-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 300.0, 68.0, 45.0, 20.0 ], "text" : "DECAY" } },
			{ "box" : { "id" : "obj-decay", "maxclass" : "number", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 350.0, 68.0, 50.0, 22.0 ], "minimum" : 10, "maximum" : 5000 } },
			{ "box" : { "id" : "obj-pd", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 350.0, 98.0, 100.0, 22.0 ], "text" : "prepend decay_ms" } },
			{ "box" : { "id" : "obj-exc-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 470.0, 48.0, 90.0, 20.0 ], "text" : "EXCITER (0/1)" } },
			{ "box" : { "id" : "obj-exc", "maxclass" : "number", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 470.0, 68.0, 40.0, 22.0 ], "minimum" : 0, "maximum" : 1 } },
			{ "box" : { "id" : "obj-pe", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 470.0, 98.0, 115.0, 22.0 ], "text" : "prepend exciter_type" } },
			{ "box" : { "id" : "obj-bod-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 600.0, 48.0, 80.0, 20.0 ], "text" : "BODY (0/1)" } },
			{ "box" : { "id" : "obj-bod", "maxclass" : "number", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 600.0, 68.0, 40.0, 22.0 ], "minimum" : 0, "maximum" : 1 } },
			{ "box" : { "id" : "obj-pbt", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 600.0, 98.0, 105.0, 22.0 ], "text" : "prepend body_type" } },
			{ "box" : { "id" : "obj-macro-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 30.0, 140.0, 200.0, 20.0 ], "text" : "== MACROS (0. - 1.) ==" } },
			{ "box" : { "id" : "obj-sl", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 30.0, 163.0, 55.0, 20.0 ], "text" : "STRESS" } },
			{ "box" : { "id" : "obj-m1", "maxclass" : "flonum", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 30.0, 183.0, 55.0, 22.0 ] } },
			{ "box" : { "id" : "obj-pm1", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 30.0, 213.0, 85.0, 22.0 ], "text" : "prepend stress" } },
			{ "box" : { "id" : "obj-scl", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 130.0, 163.0, 40.0, 20.0 ], "text" : "SCAR" } },
			{ "box" : { "id" : "obj-m2", "maxclass" : "flonum", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 130.0, 183.0, 55.0, 22.0 ] } },
			{ "box" : { "id" : "obj-pm2", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 130.0, 213.0, 70.0, 22.0 ], "text" : "prepend scar" } },
			{ "box" : { "id" : "obj-wl", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 230.0, 163.0, 55.0, 20.0 ], "text" : "WEIGHT" } },
			{ "box" : { "id" : "obj-m3", "maxclass" : "flonum", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 230.0, 183.0, 55.0, 22.0 ] } },
			{ "box" : { "id" : "obj-pm3", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 230.0, 213.0, 85.0, 22.0 ], "text" : "prepend weight" } },
			{ "box" : { "id" : "obj-bl", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 330.0, 163.0, 50.0, 20.0 ], "text" : "BLOOM" } },
			{ "box" : { "id" : "obj-m4", "maxclass" : "flonum", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 330.0, 183.0, 55.0, 22.0 ] } },
			{ "box" : { "id" : "obj-pm4", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 330.0, 213.0, 85.0, 22.0 ], "text" : "prepend bloom" } },
			{ "box" : { "id" : "obj-ml", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 430.0, 163.0, 40.0, 20.0 ], "text" : "MIST" } },
			{ "box" : { "id" : "obj-m5", "maxclass" : "flonum", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 430.0, 183.0, 55.0, 22.0 ] } },
			{ "box" : { "id" : "obj-pm5", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 430.0, 213.0, 75.0, 22.0 ], "text" : "prepend mist" } },
			{ "box" : { "id" : "obj-hl", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 530.0, 163.0, 40.0, 20.0 ], "text" : "HEAT" } },
			{ "box" : { "id" : "obj-m6", "maxclass" : "flonum", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 530.0, 183.0, 55.0, 22.0 ] } },
			{ "box" : { "id" : "obj-pm6", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 530.0, 213.0, 100.0, 22.0 ], "text" : "prepend heat_macro" } },
			{ "box" : { "id" : "obj-drl", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 650.0, 163.0, 40.0, 20.0 ], "text" : "DRIFT" } },
			{ "box" : { "id" : "obj-m7", "maxclass" : "flonum", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 650.0, 183.0, 55.0, 22.0 ] } },
			{ "box" : { "id" : "obj-pm7", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 650.0, 213.0, 105.0, 22.0 ], "text" : "prepend drift_param" } },
			{ "box" : { "id" : "obj-del", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 770.0, 163.0, 55.0, 20.0 ], "text" : "DENSITY" } },
			{ "box" : { "id" : "obj-m8", "maxclass" : "flonum", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "", "bang" ], "patching_rect" : [ 770.0, 183.0, 55.0, 22.0 ] } },
			{ "box" : { "id" : "obj-pm8", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 770.0, 213.0, 115.0, 22.0 ], "text" : "prepend density_param" } },
			{ "box" : { "id" : "obj-lb", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "bang" ], "patching_rect" : [ 30.0, 250.0, 58.0, 22.0 ], "text" : "loadbang" } },
			{ "box" : { "id" : "obj-init", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 30.0, 280.0, 700.0, 22.0 ], "text" : "pitch 60, decay_ms 200, stress 0.3, bloom 0.3, scar 0, weight 0.5, mist 0.2, heat_macro 0.3, drift_param 0, density_param 0.5" } },
			{ "box" : { "id" : "obj-gen", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "signal" ], "patching_rect" : [ 30.0, 320.0, 200.0, 22.0 ], "text" : "gen~",
				"patcher" : {
					"fileversion" : 1,
					"appversion" : { "major" : 9, "minor" : 0, "revision" : 0, "architecture" : "x64", "modernui" : 1 },
					"rect" : [ 0.0, 0.0, 800.0, 600.0 ],
					"editing_bgcolor" : [ 0.65, 0.65, 0.65, 1.0 ],
					"boxes" : [
						{ "box" : { "id" : "obj-gin", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 50.0, 14.0, 30.0, 22.0 ], "text" : "in 1" } },
						{ "box" : { "id" : "obj-gcb", "maxclass" : "codebox", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 50.0, 50.0, 700.0, 450.0 ], "code" : "Param pitch(60);\nParam decay_ms(200);\nParam exciter_type(0);\nParam body_type(0);\nParam stress(0.3);\nParam bloom(0.3);\nParam scar(0);\nParam weight(0.5);\nParam mist(0.2);\nParam heat_macro(0.3);\nParam drift_param(0);\nParam density_param(0.5);\n\nHistory prev_trig(0);\nHistory pressure(0);\nHistory heat_state(0);\nHistory fatigue(0);\nHistory exc_car_phase(0);\nHistory exc_mod_phase(0);\nHistory exc_env(0);\nHistory noise_filt(0);\nHistory ry1_a(0);\nHistory ry2_a(0);\nHistory ry1_b(0);\nHistory ry2_b(0);\nHistory ry1_c(0);\nHistory ry2_c(0);\nHistory ry1_d(0);\nHistory ry2_d(0);\nHistory comb_lp(0);\nHistory halo_env(0);\nHistory main_env(0);\nDelay comb_d(8820);\n\ntrig_on = (in1 > 0.5) * (prev_trig <= 0.5);\nvel = in1;\nprev_trig = in1;\n\nif (trig_on) {\n    pressure = min(pressure + vel * (0.3 + stress * 0.7) * (1 - pressure), 1);\n    fatigue = min(fatigue + 0.02 * (1 - fatigue), 1);\n    exc_env = 1;\n    halo_env = vel * mist;\n    main_env = vel;\n}\n\np_decay = 0.00002 + (1 - stress) * 0.00008;\npressure = pressure * (1 - p_decay);\nheat_state = heat_state + (pressure - heat_state) * 0.0002;\nheat_state = heat_state * (1 - 0.00005);\nfatigue = fatigue * (1 - 0.000002);\nstiffness = fatigue * 0.6 + pressure * 0.4;\n\neff_heat = clamp(heat_macro + heat_state * 0.5, 0, 1);\neff_scar = clamp(scar + pressure * stress, 0, 1);\np_mod = pitch + noise() * pressure * drift_param * 2;\nbase_freq = mtof(clamp(p_mod, 10, 130));\nw_scale = 1 - weight * 0.8;\nbody_freq = base_freq * w_scale;\n\ne_decay = 0.001 + density_param * 0.003;\nexc_env = exc_env * (1 - e_decay);\n\nexciter_out = 0;\nif (exciter_type < 0.5) {\n    fm_r = 1.41 + eff_heat * 2;\n    mf = base_freq * fm_r;\n    fm_idx = (8 + eff_heat * 12) * exc_env;\n    exc_mod_phase = wrap(exc_mod_phase + mf / samplerate, 0, 1);\n    mod_sig = sin(exc_mod_phase * twopi) * fm_idx;\n    exc_car_phase = wrap(exc_car_phase + base_freq / samplerate, 0, 1);\n    exciter_out = sin(exc_car_phase * twopi + mod_sig) * exc_env;\n} else {\n    n = noise();\n    cutoff = base_freq * (2 + eff_heat * 8);\n    coeff = clamp(1 - exp(-twopi * cutoff / samplerate), 0.001, 0.999);\n    noise_filt = noise_filt + (n - noise_filt) * coeff;\n    exciter_out = noise_filt * 4 * exc_env;\n}\n\nbody_out = 0;\neff_Q = clamp(0.995 - fatigue * 0.3, 0.8, 0.999);\n\nif (body_type < 0.5) {\n    w1 = twopi * body_freq * 1.0 / samplerate;\n    r1 = eff_Q;\n    ya = exciter_out + 2 * r1 * cos(w1) * ry1_a - r1 * r1 * ry2_a;\n    ry2_a = ry1_a; ry1_a = ya;\n    w2 = twopi * body_freq * (1.347 + stiffness * 0.15) / samplerate;\n    r2 = eff_Q * 0.99;\n    yb = exciter_out + 2 * r2 * cos(w2) * ry1_b - r2 * r2 * ry2_b;\n    ry2_b = ry1_b; ry1_b = yb;\n    w3 = twopi * body_freq * (1.891 + stiffness * 0.2) / samplerate;\n    r3 = eff_Q * 0.98;\n    yc = exciter_out + 2 * r3 * cos(w3) * ry1_c - r3 * r3 * ry2_c;\n    ry2_c = ry1_c; ry1_c = yc;\n    w4 = twopi * body_freq * (2.534 + stiffness * 0.3) / samplerate;\n    r4 = eff_Q * 0.97;\n    yd = exciter_out + 2 * r4 * cos(w4) * ry1_d - r4 * r4 * ry2_d;\n    ry2_d = ry1_d; ry1_d = yd;\n    body_out = (ya + yb * 0.7 + yc * 0.45 + yd * 0.3) * 0.25;\n} else {\n    d_samps = clamp(samplerate / body_freq, 2, 8000);\n    fb = eff_Q * 0.9;\n    delayed = comb_d.read(d_samps);\n    d_coeff = 0.3 + fatigue * 0.4;\n    comb_lp = comb_lp + (delayed - comb_lp) * d_coeff;\n    comb_d.write(exciter_out + comb_lp * fb);\n    body_out = delayed;\n}\n\nfold_d = 1 + eff_scar * 4;\nfractured = body_out;\nif (eff_scar > 0.01) {\n    biased = body_out + pressure * 0.3;\n    folded = asin(sin(biased * fold_d * 1.5707963)) * 0.6366197;\n    fractured = body_out * (1 - eff_scar) + folded * eff_scar;\n}\n\nbl_decay = 0.0001 + bloom * 0.001;\nhalo_env = halo_env * (1 - bl_decay);\nh_out = noise() * halo_env * clamp(body_freq * 2 / samplerate, 0.01, 0.49) * 4;\n\nenv_rate = 1.0 / max(decay_ms * samplerate / 1000, 1);\nmain_env = main_env * (1 - env_rate);\n\nmixed = fractured * (1 - mist * 0.5) + h_out;\nout1 = mixed * main_env;" } },
						{ "box" : { "id" : "obj-gout", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 50.0, 520.0, 35.0, 22.0 ], "text" : "out 1" } }
					],
					"lines" : [
						{ "patchline" : { "source" : [ "obj-gin", 0 ], "destination" : [ "obj-gcb", 0 ] } },
						{ "patchline" : { "source" : [ "obj-gcb", 0 ], "destination" : [ "obj-gout", 0 ] } }
					]
				}
			} },
			{ "box" : { "id" : "obj-out-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 30.0, 355.0, 100.0, 20.0 ], "text" : "== OUTPUT ==" } },
			{ "box" : { "id" : "obj-atten", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "signal" ], "patching_rect" : [ 30.0, 375.0, 55.0, 22.0 ], "text" : "*~ 0.3" } },
			{ "box" : { "id" : "obj-gain", "maxclass" : "gain~", "numinlets" : 1, "numoutlets" : 2, "outlettype" : [ "signal", "" ], "patching_rect" : [ 30.0, 405.0, 200.0, 30.0 ], "parameter_enable" : 0, "orientation" : 1 } },
			{ "box" : { "id" : "obj-scope", "maxclass" : "scope~", "numinlets" : 2, "numoutlets" : 0, "patching_rect" : [ 300.0, 370.0, 200.0, 80.0 ] } },
			{ "box" : { "id" : "obj-meter", "maxclass" : "meter~", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "float" ], "patching_rect" : [ 30.0, 445.0, 200.0, 20.0 ] } },
			{ "box" : { "id" : "obj-dac", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 0, "patching_rect" : [ 30.0, 480.0, 60.0, 22.0 ], "text" : "dac~ 1 2" } },
			{ "box" : { "id" : "obj-audio-tog", "maxclass" : "toggle", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "int" ], "patching_rect" : [ 120.0, 455.0, 30.0, 30.0 ] } },
			{ "box" : { "id" : "obj-sel01", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 3, "outlettype" : [ "bang", "bang", "" ], "patching_rect" : [ 120.0, 490.0, 55.0, 22.0 ], "text" : "sel 0 1" } },
			{ "box" : { "id" : "obj-msg-stop", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 120.0, 520.0, 35.0, 22.0 ], "text" : "stop" } },
			{ "box" : { "id" : "obj-msg-start", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 170.0, 520.0, 65.0, 22.0 ], "text" : "startwindow" } },
			{ "box" : { "id" : "obj-audio-label", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 160.0, 460.0, 80.0, 20.0 ], "text" : "Audio ON/OFF" } },
			{ "box" : { "id" : "obj-hint1", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 300.0, 455.0, 350.0, 20.0 ], "text" : "0=FM Impulse / 1=Noise Burst    0=Resonator / 1=Comb" } },
			{ "box" : { "id" : "obj-hint2", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 300.0, 475.0, 400.0, 20.0 ], "text" : "Click button rapidly to build pressure. Silence cools it down." } }
		],
		"lines" : [
			{ "patchline" : { "source" : [ "obj-btn", 0 ], "destination" : [ "obj-click", 0 ] } },
			{ "patchline" : { "source" : [ "obj-click", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pitch", 0 ], "destination" : [ "obj-pp", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pp", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-decay", 0 ], "destination" : [ "obj-pd", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pd", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-exc", 0 ], "destination" : [ "obj-pe", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pe", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-bod", 0 ], "destination" : [ "obj-pbt", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pbt", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-m1", 0 ], "destination" : [ "obj-pm1", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pm1", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-m2", 0 ], "destination" : [ "obj-pm2", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pm2", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-m3", 0 ], "destination" : [ "obj-pm3", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pm3", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-m4", 0 ], "destination" : [ "obj-pm4", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pm4", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-m5", 0 ], "destination" : [ "obj-pm5", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pm5", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-m6", 0 ], "destination" : [ "obj-pm6", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pm6", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-m7", 0 ], "destination" : [ "obj-pm7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pm7", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-m8", 0 ], "destination" : [ "obj-pm8", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pm8", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-lb", 0 ], "destination" : [ "obj-init", 0 ] } },
			{ "patchline" : { "source" : [ "obj-init", 0 ], "destination" : [ "obj-gen", 0 ] } },
			{ "patchline" : { "source" : [ "obj-gen", 0 ], "destination" : [ "obj-atten", 0 ] } },
			{ "patchline" : { "source" : [ "obj-atten", 0 ], "destination" : [ "obj-gain", 0 ] } },
			{ "patchline" : { "source" : [ "obj-gain", 0 ], "destination" : [ "obj-dac", 0 ] } },
			{ "patchline" : { "source" : [ "obj-gain", 0 ], "destination" : [ "obj-dac", 1 ] } },
			{ "patchline" : { "source" : [ "obj-gain", 0 ], "destination" : [ "obj-scope", 0 ] } },
			{ "patchline" : { "source" : [ "obj-gain", 0 ], "destination" : [ "obj-meter", 0 ] } },
			{ "patchline" : { "source" : [ "obj-audio-tog", 0 ], "destination" : [ "obj-sel01", 0 ] } },
			{ "patchline" : { "source" : [ "obj-sel01", 0 ], "destination" : [ "obj-msg-stop", 0 ] } },
			{ "patchline" : { "source" : [ "obj-sel01", 1 ], "destination" : [ "obj-msg-start", 0 ] } },
			{ "patchline" : { "source" : [ "obj-msg-stop", 0 ], "destination" : [ "obj-dac", 0 ] } },
			{ "patchline" : { "source" : [ "obj-msg-start", 0 ], "destination" : [ "obj-dac", 0 ] } }
		]
	}
}
